/*☺
Individual JavaScript for [Project name]
*/


/* SCRIPT DIRECTORY

jQuery Scripts

1. Cache some repetedly used elements
2. Menu (accordion menu or dropdown menu, according to screen size)
3. ScrollToFixed application
4. Cookie information banner
5. Sisyphus initialisation

*/


/* =============================================================================
   1.  Cache some repeatedly used elements
   ========================================================================== */

var mvl_main_navigation_container = $('.main-navigation-container');
var mvl_accordion_toggle = $('.main-navigation-toggle');
var mvl_main_navigation = $('.main-navigation');
var mvl_main_navigation_list = $('.main-navigation-list');
var mvl_dropdown_toggles_li = mvl_main_navigation_list.find('.has_children');
var mvl_dropdown_toggles_a = mvl_dropdown_toggles_li.children('a');
var mvl_page_footer_container = $('.page-footer-container');


/* =============================================================================
   2.  Menu (accordion menu or dropdown menu, according to screen size)
   ========================================================================== */

$(document).ready(function() {

	// remove href attribute from all menu links that are used as submenu toggle links
	mvl_dropdown_toggles_a.each(function() {
		var mvl_dropdown_href = $(this).attr('href');
		$(this).attr('data-target', mvl_dropdown_href).removeAttr('href');
	});

	// add functionality to "Navigtion" button which reveals the accordion menu
	mvl_accordion_toggle.click(function() {
		mvl_accordion_toggle.toggleClass('show-submenu');
		mvl_dropdown_toggles_li.removeClass('show-submenu'); // hide all "inner" accordion submenus
	});

	// accordion resp. dropdown functionality
	mvl_dropdown_toggles_a.click(function() {
		var mvl_dropdown_toggle_li = $(this).parent('li'); // the <li class="has_children"> which is a direct parent of the clicked <a href="…">
		mvl_dropdown_toggle_li.toggleClass('show-submenu'); // show resp. hide clicked dropdown menu
		mvl_dropdown_toggle_li
				.siblings('.show-submenu')
				.removeClass('show-submenu'); // hide all dropdown menus below all siblings of the <li class="has_children"> which is a direct parent of the clicked <a href="…">
		mvl_dropdown_toggle_li
				.find('.show-submenu')
				.removeClass('show-submenu'); // hide all dropdown menus below clicked <a href="…">
	});

});

// accordion menu for smaller screen sizes
enquire.register('screen and (max-width: 1019px)', {
	match: function() {
		mvl_main_navigation_list.css('max-height', $(window).height() - $(mvl_accordion_toggle).outerHeight()); // max height for dropped down menu
		mvl_main_navigation_container.bind('clickoutside', function() {
			mvl_accordion_toggle.removeClass('show-submenu'); // hide accordion menus when the user clicks anywhere outside the menu area
			mvl_dropdown_toggles_li.removeClass('show-submenu'); // hide all dropdown menus when the user clicks anywhere outside the menu area
		});
	},
	unmatch: function() {
		mvl_main_navigation_container.unbind('clickoutside');
		mvl_accordion_toggle.removeClass('show-submenu');
		mvl_main_navigation_list
			.css('max-height', '')
			.find('.show-submenu')
			.removeClass('show-submenu');
		mvl_accordion_toggle.removeClass('show-submenu');
	}
});

// dropdown menu for bigger screen sizes
enquire.register('screen and (min-width: 1020px)', {
	match: function() {
		mvl_main_navigation_list.bind('clickoutside', function() {
			mvl_dropdown_toggles_li.removeClass('show-submenu'); // hide all dropdown menus when the user clicks anywhere outside the menu area
		});
	},
	unmatch: function() {
		mvl_main_navigation_list
				.unbind('clickoutside')
				.find('.show-submenu')
				.removeClass('show-submenu');
	}
});


/* =============================================================================
   3.  ScrollToFixed application
   ========================================================================== */

$(document).ready(function() {
	mvl_main_navigation_container.scrollToFixed({
		dontSetWidth: true
	});
});


/* =============================================================================
   4.  Cookie information banner
   ========================================================================== */

var mvl_page_footer_container_margin_bottom = '0px';

$(document).ready(function() {
	// Configuration:
	// Enter the text for the cookie banner, including a link to your privacy policy.
	// You should move this variable declaration to your HTML document if you want to fill it
	// with information generated by a CMS, e.g. different messages for a multi-language website.
	var cookieInfoBannerText = 'Cookies help deliver this website. By using this website, you agree to the website’s use of cookies, as detailed in the <a href="#">privacy policy</a>.';

	if ($.cookie('mvl_cookiePermission') != 'ok') {
		mvl_page_footer_container.after('<div class="cookie-information-banner-container clearfix"><div class="wrapper"><div class="cookie-information-banner"><p class="cookie-information">' + cookieInfoBannerText +' <button type="button" class="cookie-information-banner-close">OK</button></p></div></div></div>');
		mvl_page_footer_container_margin_bottom = $('.cookie-information-banner-container').outerHeight() + 'px';
		mvl_page_footer_container.css('margin-bottom', mvl_page_footer_container_margin_bottom);
	}
	$('.cookie-information-banner-close').click(function(event) {
		event.preventDefault();
		mvl_page_footer_container.css('margin-bottom', '0');
		$('.cookie-information-banner-container').hide();
		$.cookie('mvl_cookiePermission', 'ok', { expires: 3650, path: '/' });
	});
});

$(window).resize(function() {
	if ($.cookie('mvl_cookiePermission') != 'ok') {
		mvl_page_footer_container_margin_bottom = $('.cookie-information-banner-container').outerHeight() + 'px';
		mvl_page_footer_container.css('margin-bottom', mvl_page_footer_container_margin_bottom);
	}
});


/* =============================================================================
   5.  Sisyphus initialisation
   ========================================================================== */

$(document).ready(function() {
	if ($('form').length > 0) {
		$('form').sisyphus();
	}
});
