#===============================================================================
# Michael van Laar’s Sass Lint preferences
#===============================================================================





#-------------------------------------------------------------------------------
# Linter options
# https://github.com/sasstools/sass-lint/tree/master/docs/options
#-------------------------------------------------------------------------------


options:
  merge-default-rules: true
  formatter: stylish





#-------------------------------------------------------------------------------
# File options
#-------------------------------------------------------------------------------


files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'vendor/**/*.*'





#-------------------------------------------------------------------------------
# Rule configuration
# https://github.com/sasstools/sass-lint/tree/master/docs/rules
#-------------------------------------------------------------------------------


rules:


  # Extends

  extends-before-mixins: 1

  extends-before-declarations: 1

  placeholder-in-extend: 1


  # Mixins

  mixins-before-declarations:
    - 1
    -
      exclude:
        - mvl-respond-to


  # Line Spacing

  one-declaration-per-line: 1

  empty-line-between-blocks:
    - 1
    -
      include: true
      allow-single-line-rulesets: false

  single-line-per-selector: 1


  # Disallows

  no-attribute-selectors: 0

  no-color-hex: 0

  no-color-keywords: 1

  no-color-literals: 0

  no-combinators: 0

  no-css-comments: 1

  no-debug: 1

  no-disallowed-properties: 0

  no-duplicate-properties: 1

  no-empty-rulesets: 1

  no-extends: 2

  no-ids: 0

  no-important: 0

  no-invalid-hex: 2

  no-mergeable-selectors: 1

  no-misspelled-properties: 2

  no-qualifying-elements: 0

  no-trailing-whitespace: 1

  no-trailing-zero: 1

  no-transition-all: 0

  no-universal-selectors: 0

  no-url-domains: 0

  no-url-protocols: 0

  no-vendor-prefixes: 2

  no-warn: 1

  property-units: 0


  # Nesting

  declarations-before-nesting: 1

  force-attribute-nesting: 0

  force-element-nesting: 0

  force-pseudo-nesting: 0


  # Name Formats

  class-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'Class should be written in BEM format'


  function-name-format:
    - 1
    -
      allow-leading-underscore: true
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'Function name should be written in BEM format (like classes)'

  id-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'ID should be written in BEM format (like classes)'

  mixin-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'Mixin name should be written in BEM format (like classes)'

  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'Placeholder should be written in BEM format (like classes)'

  variable-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^(_)?[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
      convention-explanation: 'Variable should be written in BEM format (like classes)'


  # Style Guide

  attribute-quotes: 1

  bem-depth:
    - 1
    -
      max-depth: 1

  border-zero:
    - 1
    -
      convention: '0'

  brace-style:
    - 1
    -
      style: '1tbs'
      allow-single-line: false

  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false

  empty-args:
    - 1
    -
      include: false

  hex-length:
    - 1
    -
      style: short

  hex-notation:
    - 1
    -
      style: lowercase

  indentation: 0

  leading-zero:
    - 1
    -
      include: true

  max-line-length: 0

  max-file-line-count: 0

  nesting-depth:
    - 1
    -
      max-depth: 3

  property-sort-order:
    - 1
    -
      order:
        - font
        - font-family
        - font-size
        - font-weight
        - font-style
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - line-height
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        - display
        - visibility
        - float
        - clear
        - overflow
        - overflow-x
        - overflow-y
        - -ms-overflow-x
        - -ms-overflow-y
        - clip
        - clip-path
        - zoom
        - flex-direction
        - flex-wrap
        - flex-flow
        - justify-content
        - align-items
        - align-content
        - order
        - flex-grow
        - flex-shrink
        - flex-basis
        - flex
        - align-self
        - -webkit-box-sizing
        - -moz-box-sizing
        - box-sizing
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        - content
        - quotes
        - counter-reset
        - counter-increment
        - resize
        - cursor
        - -webkit-user-select
        - -moz-user-select
        - -ms-user-select
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - -webkit-transition
        - -moz-transition
        - -ms-transition
        - -o-transition
        - transition
        - -webkit-transition-delay
        - -moz-transition-delay
        - -ms-transition-delay
        - -o-transition-delay
        - transition-delay
        - -webkit-transition-timing-function
        - -moz-transition-timing-function
        - -ms-transition-timing-function
        - -o-transition-timing-function
        - transition-timing-function
        - -webkit-transition-duration
        - -moz-transition-duration
        - -ms-transition-duration
        - -o-transition-duration
        - transition-duration
        - -webkit-transition-property
        - -moz-transition-property
        - -ms-transition-property
        - -o-transition-property
        - transition-property
        - -webkit-transform
        - -moz-transform
        - -ms-transform
        - -o-transform
        - transform
        - -webkit-transform-origin
        - -moz-transform-origin
        - -ms-transform-origin
        - -o-transform-origin
        - transform-origin
        - -webkit-animation
        - -moz-animation
        - -ms-animation
        - -o-animation
        - animation
        - -webkit-animation-name
        - -moz-animation-name
        - -ms-animation-name
        - -o-animation-name
        - animation-name
        - -webkit-animation-duration
        - -moz-animation-duration
        - -ms-animation-duration
        - -o-animation-duration
        - animation-duration
        - -webkit-animation-play-state
        - -moz-animation-play-state
        - -ms-animation-play-state
        - -o-animation-play-state
        - animation-play-state
        - -webkit-animation-timing-function
        - -moz-animation-timing-function
        - -ms-animation-timing-function
        - -o-animation-timing-function
        - animation-timing-function
        - -webkit-animation-delay
        - -moz-animation-delay
        - -ms-animation-delay
        - -o-animation-delay
        - animation-delay
        - -webkit-animation-iteration-count
        - -moz-animation-iteration-count
        - -ms-animation-iteration-count
        - -o-animation-iteration-count
        - animation-iteration-count
        - -webkit-animation-direction
        - -moz-animation-direction
        - -ms-animation-direction
        - -o-animation-direction
        - animation-direction
        - text-align
        - -webkit-text-align-last
        - -moz-text-align-last
        - -ms-text-align-last
        - text-align-last
        - vertical-align
        - white-space
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-indent
        - -ms-text-justify
        - text-justify
        - letter-spacing
        - word-spacing
        - -ms-writing-mode
        - text-outline
        - text-transform
        - text-wrap
        - text-overflow
        - -ms-text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - -ms-word-wrap
        - word-wrap
        - word-break
        - -ms-word-break
        - -moz-tab-size
        - -o-tab-size
        - tab-size
        - -webkit-hyphens
        - -moz-hyphens
        - hyphens
        - pointer-events
        - opacity
        - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha
        - -ms-interpolation-mode
        - color
        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - -webkit-border-radius
        - -moz-border-radius
        - border-radius
        - -webkit-border-top-left-radius
        - -moz-border-radius-topleft
        - border-top-left-radius
        - -webkit-border-top-right-radius
        - -moz-border-radius-topright
        - border-top-right-radius
        - -webkit-border-bottom-right-radius
        - -moz-border-radius-bottomright
        - border-bottom-right-radius
        - -webkit-border-bottom-left-radius
        - -moz-border-radius-bottomleft
        - border-bottom-left-radius
        - -webkit-border-image
        - -moz-border-image
        - -o-border-image
        - border-image
        - -webkit-border-image-source
        - -moz-border-image-source
        - -o-border-image-source
        - border-image-source
        - -webkit-border-image-slice
        - -moz-border-image-slice
        - -o-border-image-slice
        - border-image-slice
        - -webkit-border-image-width
        - -moz-border-image-width
        - -o-border-image-width
        - border-image-width
        - -webkit-border-image-outset
        - -moz-border-image-outset
        - -o-border-image-outset
        - border-image-outset
        - -webkit-border-image-repeat
        - -moz-border-image-repeat
        - -o-border-image-repeat
        - border-image-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - background
        - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
        - background-color
        - background-image
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - -ms-background-position-x
        - background-position-y
        - -ms-background-position-y
        - -webkit-background-clip
        - -moz-background-clip
        - background-clip
        - background-origin
        - -webkit-background-size
        - -moz-background-size
        - -o-background-size
        - background-size
        - box-decoration-break
        - -webkit-box-shadow
        - -moz-box-shadow
        - box-shadow
        - filter:progid:DXImageTransform.Microsoft.gradient
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.gradient
        - text-shadow
      ignore-custom-properties: true

  pseudo-element: 1

  quotes:
    - 1
    -
      style: single

  shorthand-values:
    - 1
    -
      allowed-shorthands:
        - 1
        - 2
        - 3

  url-quotes: 1

  variable-for-property: 0

  zero-unit:
    - 1
    -
      include: false


  # Inner Spacing

  space-after-comma:
    - 1
    -
      include: true

  space-before-colon:
    - 1
    -
      include: false

  space-after-colon:
    - 1
    -
      include: true

  space-before-brace:
    - 1
    -
      include: true

  space-before-bang:
    - 1
    -
      include: true

  space-after-bang:
    - 1
    -
      include: false

  space-between-parens:
    - 1
    -
      include: false

  space-around-operator:
    - 1
    -
      include: true


  # Final Items

  trailing-semicolon:
    - 1
    -
      include: true

  final-newline:
    - 1
    -
      include: true
